apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: employee-service-image
        imagePullPolicy: IfNotPresent  # Replace with your built Docker image name
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31011   # You can specify a custom NodePort, or omit it for automatic allocation
  type: NodePort

